name = "opensheet"
main = "index.js"
account_id = "9455b1c30226693b3c467371f90c1edb"
compatibility_date = "2023-10-20"

# Uncomment if you don’t have a custom domain.
workers_dev = true

# For custom domain — comment out if you don’t have a custom domain.
# route = "opensheet.elk.sh/*"
